--- #YAML:1.0
name:                Quietly-Confident
version:             0.02
abstract:            ~
license:             perl
author:              
    - TLINDEN
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Config::General:               0
    Git::Repository:               0
    HTTP::Server::Brick:           0
    Moo:                           0
    Sub::Quote:                    0
    Template:                      0
    Text::Markdown:                0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
