--- #YAML:1.0
name:               Quietly-Confident
version:            0.10
abstract:           ~
author:
    - TLINDEN
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::General:      0
    Git::Repository:      0
    HTTP::Server::Brick:  0
    Moo:                  0
    Sub::Quote:           0
    Template:             0
    Text::Markdown:       0
    URI::Encode:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
